# Generated by Django 5.2 on 2025-04-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site_url', models.CharField(max_length=10000)),
                ('site_image_url', models.CharField(max_length=10000)),
                ('feedback', models.CharField(default='None', max_length=10000, null=True)),
            ],
        ),
    ]
